blog-after/config/routes.rb
Blog::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  root to: 'articles#index'
  resources :articles
end

blog-after/app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
end

blog-after/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  attr_accessible :email, :password, :password_confirmation
  
  validates_uniqueness_of :email
end

blog-after/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  
  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

blog-after/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authorize, only: [:edit, :update]
  
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      redirect_to @article, notice: "Article has been updated."
    else
      render "edit"
    end
  end
end

blog-after/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

blog-after/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end
end

blog-after/app/helpers/application_helper.rb
module ApplicationHelper
end

blog-after/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog-after/app/helpers/sessions_helper.rb
module SessionsHelper
end

blog-after/app/helpers/users_helper.rb
module UsersHelper
end

blog-after/app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :author_name %><br />
    <%= f.text_field :author_name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :rows => 12, :cols => 35 %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

blog-after/app/views/articles/index.html.erb
<h1>Articles</h1>

<div id="articles">
<% @articles.each do |article| %>
  <h2>
    <%= link_to article.name, article %>
  </h2>
  <div class="info">
    by <%= article.author_name %>
    on <%= article.published_at.strftime('%b %d, %Y') %>
  </div>
  <div class="content"><%= article.content %></div>
<% end %>
</div>

blog-after/app/views/articles/show.html.erb
<h1><%= @article.name %></h1>
<%= @article.content %>
<p>
  <%= link_to "Edit", edit_article_path(@article) %> |
  <%= link_to "Browse Articles", articles_path %>
</p>

blog-after/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <div id="user_header">
        <% if current_user %>
          Logged in as <%= current_user.email %>.
          <%= link_to "Log Out", logout_path %>
        <% else %>
          <%= link_to "Sign Up", signup_path %> or
          <%= link_to "Log In", login_path %>
        <% end %>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

blog-after/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>